# Generated by Django 3.0.4 on 2020-03-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
