# Generated by Django 2.2.12 on 2020-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProductos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.TextField(default='', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
